### ISSUE TITLE
Code Health (Q3 2023)

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#122]
**Key Results**:  
- [x] https://github.com/medic/cht-core/issues/7356
- [ ] [DHIS2 import reports a conflict](https://github.com/medic/cht-core/issues/7447)
- [ ] [Credentials exposed in logs #7990](https://github.com/medic/cht-core/issues/7990)
- [x] [Uplift message format to @messageformat/core #7370](https://github.com/medic/cht-core/issues/7370)

**Description**: Increasing the health of CHT as a whole over time, piece by piece.

**Comment by andrablaj** [comment]
Closing as marked as `Done`
