### ISSUE TITLE
CHT Code Health (Q3 2024)

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-roadmap#137]
**Key Results:** 
- [ ] [Credentials exposed in logs #7990](https://github.com/medic/cht-core/issues/7990)
- [x] [Outbound push cron config error #8947](https://github.com/medic/cht-core/issues/8947)
- [ ] Send Outbound Push requests in a single payload [#8981](https://github.com/medic/cht-core/issues/8981)
- [ ] [Cyber security]: Split RDBMS into multiple separate instances. At this stage moving one project from rdbms to a single RDS instance and documenting how to do it would be great.
- ~~[DHIS2 import reports a conflict](https://github.com/medic/cht-core/issues/7447)~~
