### ISSUE TITLE
Remote onboarding, training, support for end users

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-roadmap#32]
**This initiative focuses on enabling a user to pick up a CHT app and begin to use it without in-person training.**

## Opportunity

We should empower our users to use the CHT app on their own. This would allow for more scalable deployments and ensure end-user safety when it comes to COVID-related (no-touch) protocols by not having to partake in in-person group training sessions (or partake in fewer sessions). We should also provide automated and self-service support to users who are experiencing workflow or technical difficulties.

### Epic: Telemetry and/or usability testing to support onboarding improvements
- [ ] [User test plan](https://docs.google.com/forms/d/1yutW4Wcpnbhmdq5zbJAz-z6BTwzbsstMFzxncXqBc-A/edit)

### Epic: Registration
- As a user I want to log into the CHT for the first time with speed and ease so I can get started with using the app
- As a supervisor I want to know which CHWs have registered or logged in so I can offer support to those who have not
- [x] *Prerequisite*: none
- [x] https://github.com/medic/cht-core/issues/6380
- [ ] *Evaluation criteria*: 

### Epic: Updates and Announcements
- As a user I want to be notified when there are new features or workflows in my app so that I am always up to date on the actions I can take, and how
- As a user I want to be notified when there are updates to my forms, tasks or targets so that I can ensure I am doing my work correctly and efficiently
- [ ] *Prerequisite*: None
- [x] https://github.com/medic/cht-core/issues/6598
- [ ] *Evaluation criteria*: 

### Epic: Self-Service Help
- As a user I want to proactively ask for help when I run into any technical/workflow issues so that I can serve my community confidently 
- As a supervisor I want to effectively receive and manage my CHWs requests for help so I can prioritize and track my support accordingly 
- [ ] *Prerequisite*: None
- [ ] https://github.com/medic/cht-core/issues/6659
- [ ] *Evaluation criteria*: 

### Epic: General Education
- As a user I want to understand the concepts and functionality of my app so I can utilize all features to do my best work
- As a user I want to practice workflows and actions before to ensure mastery before beginning assessments with families
As a user I want to revisit the general education if I have not used my app in a while to review it’s capabilities and do my best work
- [ ] *Prerequisite*: [Completion of UX updates](https://github.com/medic/cht-roadmap/issues/49) 
- [ ] *Evaluation criteria*:

**Comment by n-orlowski** [comment]
https://docs.google.com/document/d/1TXBVbqQNRdnx_t5jwlWgw5_5F47szNJX3y5bxsVYCqY/edit#

Latest initiative here -–exploring short term solutions for Covid resonse + long term / configurable solutions

**Comment by n-orlowski** [comment]
FYI training and onboarding are being treated separately;` training` will use forms and not need additional core features

**Comment by n-orlowski** [comment]
Working onboarding deck [here](https://docs.google.com/presentation/d/10cQyobkYzImM-PKvnhjBcePHUcbiUh7abI1j8GFIsBQ/edit#slide=id.g917c85c8b7_0_191). Currently continuing on scoping and fleshing out these concepts further.

**Comment by MaxDiz** [comment]
Deprecated initiative on Household to Provider Messaging for future reference: https://github.com/medic/cht-roadmap/issues/45

**Comment by MaxDiz** [comment]
Deprecated initiative on improving in-app messenger UX for reference: https://github.com/medic/cht-roadmap/issues/46
