### ISSUE TITLE
Workforce management, supervision, and peer support

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-roadmap#48]
**This initiative focuses on providing Supervisors the ability to monitor CHWs performance in-app to provide better field and district level support.**

## Situation
CHW Supervisors are ultimately accountable for the overall performance of their cadre of CHWs. From a CHW Supervisors perspective, “performance management” means knowing what CHWs are doing in the field and if they are meeting their goals. The Supervisors focus is on CHW activity metrics. Activity metrics can be counted right away and are immediately actionable (in contrast to impact metrics, which take longer to know and are cumulative). If a CHW is identified as underperforming, a Supervisor can take steps to intervene with coaching, goal modifications, or other types of support. 

## Opportunity
In order for Supervisors to provide better field and district level CHW support, we’d like to provide CHW Supervisors with the ability to monitor CHW performance in-app to align with their field work environment. Since supervisors are offline users and there are phone storage limitations to giving them access to the household-level reports that generate the CHW’s Targets, there needs to be a way for the relevant CHW Target data to be viewable on their phone in summary form. A “Supervisor Targets View” will allow for viewing the performance of their CHW cadre, as well as an individual CHW’s performance, against their defined targets.  

### Epic: Aggregate CHW Performance Monitoring
Enable Supervisors to monitor aggregate CHW performance in the Targets tab to track the success of the branch as a whole, and view CHWs compared to their peers.
- [x] *Prerequisite*: none- this is the MVP for Supervisor performance monitoring based on field research
- [x] https://github.com/medic/medic/issues/4839 
- [x] https://github.com/medic/medic/issues/4840 
- [ ] *Evaluation criteria*: https://github.com/medic/medic-impact/issues/239 

### Epic: Configurable Targets for Individual CHWs
Support configurable targets for individual CHWs / Areas and store historical target data for enhanced analysis
- [ ] *Prerequisite*: two or more deployment partners express need
- [ ] https://github.com/medic/cht-core/issues/4771 (scheduled in v3.12)
- [ ] *Evaluation criteria*: Meeting target objectives is more feasible based on specific CHW areas. CHWs are meeting more of their targets, overall, or showing improvement over time.

### Epic: Ensure Regular Supervisor/CHW Interaction
Ensure that all CHWs are being visited regularly to provide added support
- [ ] *Prerequisite*: TBD
- [ ] Registration of CHW group meetings and individual Supervisor/CHW meetings
- [ ] Add “date last visited” to CHW contact card
- [ ] Add ability for Supervisor to sort tasks based on number of CHW performance tasks outstanding so Supervisors can prioritize follow-up visits 
- [ ] Add a way to filter or adjust the view on Targets to narrow down to one CHW
- [ ] https://github.com/medic/cht-core/issues/5999
- [ ] *Evaluation criteria*: TBD

### Epic: Analytics for Enhanced CHW Supervision
Deploy deeper data analytics to open up opportunities for more dynamic and enhance supervision 
- [ ] *Prerequisite*: funder support and access to clean data for buildout of use case(s)
- [ ] Trends identification and outlier detection of report data to inform Supervisor actions (see Google.org proposal)
- [ ] Identify most “at risk” CHWs, who need added coaching/training
- [ ] https://github.com/medic/cht-core/issues/6407
- [ ] *Evaluation criteria*: TBD

### Epic: Supplementary CHW Education
Supplementary CHW education materials for care workflows
- [ ] *Prerequisite*: TBD
- [ ] Make supplementary teaching materials available to CHWs as a new tab in the app, located within forms, as FAQ bots, or similar
- [ ] *Evaluation criteria*: TBD

## Additional Reference Materials
- [Folder](https://drive.google.com/drive/folders/1_xUn3FZAOmC4qRcc8FdAn8hm0leJeEEr) with added context and lots of brainstorming
- Dimagi/Medic [proposal](https://docs.google.com/document/d/1akf85R-cKejDvlWwS9b3YDywkURGpYDC7I9JWk2Fu1c/edit#heading=h.jk32bk86nybh) for Supervisor advanced data analytics
- DataKind [data confidence work](https://github.com/datakind/data-confidence) and [relevant presentation](https://slack-files.com/T024KS27X-F014T6LG7FD-7c8a01bb3e)

**Comment by MaxDiz** [comment]
deprecated initiative on CHW Incentive Programs for future reference: https://github.com/medic/cht-roadmap/issues/18

**Comment by MaxDiz** [comment]
deprecated initiative on Data Connectivity for future reference: https://github.com/medic/cht-roadmap/issues/35

**Comment by MaxDiz** [comment]
deprecated initiative on Data Confidence for future reference: https://github.com/medic/cht-roadmap/issues/21
