### ISSUE TITLE
Improved app learnability and design scalability

### ISSUE THREAD

**Issue by n-orlowski** [medic/cht-roadmap#49]
**This initiative focuses on improving the UX of the CHT. Note: These updates are to reorganize current functionality to be more intuitive and consistent with other Android experiences, not to change functionality.**

## Opportunity

There are several opportunities to improve the UX of the CHT. We can support its learnability with a clearer mental model via an updated FAB, separating positive and negative actions. This provides a better hint as to the primary actions a user should take on each page. We should also support its scalability ex. being able to have more than 5 tabs/pages and visibility into all filters at a glance, both allowing for vertical scrolling. Lastly we should adopt a mobile-first approach as the majority of our users have transitioned from desktop top mobile devices.

## Epics

Note: a prerequisite to this initiative may be https://github.com/medic/cht-core/issues/6598 to facilitate the communication of changes to the app to end users

### Epic: Telemetry and/or usability testing to support UX updates 
- [ ] *Prerequisite*: none
- [x] https://github.com/medic/cht-core/issues/6651
- [ ] [User test plan](https://docs.google.com/forms/d/1Ii9mT_hEGdAF61d_d-TVvw4VQQYE8UM9uwnu91nVaJ4/edit)

### Epic: FAB
Group positive actions within a FAB, including a title (ex. “New”) for further context and icons + labels in a grid format to see more options on the screen at once
<img width="477" alt="Screen Shot 2020-09-29 at 2 14 14 PM" src="https://user-images.githubusercontent.com/59581790/94617236-3ba58880-0277-11eb-9654-de1dfe0b3e6d.png">
- [ ] *Prerequisite*: Secondary actions must be removed from the FAB (ex. delete/edit)
- [x] https://github.com/medic/cht-core/issues/4346
- [x] https://github.com/medic/cht-core/issues/4726
- [ ] *Evaluation criteria*: 

### Epic: Secondary Actions
Grouping secondary, negative or destructive actions removed from FAB, placed in the top right corner (ex. Filter, search, bulk delete, more options) 
<img width="695" alt="Screen Shot 2020-09-29 at 2 14 56 PM" src="https://user-images.githubusercontent.com/59581790/94617305-5841c080-0277-11eb-99b9-bbbf076136af.png">
- [ ] *Prerequisite*: Should be done in tandem with FAB
- [ ] https://github.com/medic/cht-core/issues/4334 ??? 
- [ ] *Evaluation criteria*: 

### Epic: Navigation
Supporting the configuration of tabs to LHS drawer to make more scalable and provide more real estate on the screen for content + update styling to sidebar
<img width="706" alt="Screen Shot 2020-09-29 at 2 12 21 PM" src="https://user-images.githubusercontent.com/59581790/94616282-f2553900-0276-11eb-86bb-a92ff9a560fc.png">
- [ ] *Prerequisite*: Should be the last update from the initiative
- [x] https://github.com/medic/cht-core/issues/4332
- [ ] https://github.com/medic/cht-core/issues/4324
- [ ] https://github.com/medic/cht-core/issues/4333
- [ ] *Evaluation criteria*: 

### Epic: Home tab or dashboard
A landing page to provide users with a snapshot of their progress, actionable to-dos, sync status and other important information 
- [ ] *Prerequisite*: Navigation
- [ ] https://github.com/medic/cht-core/issues/3662

### Epic: System visibility status
Users should always be aware of the system status of the app, ex. what is loading and when, when errors are made and why, etc.
- [ ] *Prerequisite*: none
- [x] https://github.com/medic/cht-core/issues/4480
- [x] https://github.com/medic/cht-core/issues/5618
- [x] https://github.com/medic/cht-core/issues/5207
- [ ] https://github.com/medic/cht-core/issues/6521
- [ ] https://github.com/medic/cht-core/issues/5874
- [ ] https://github.com/medic/cht-core/issues/6391
- [ ] https://github.com/medic/medic-android/issues/49
- [ ] https://github.com/medic/cht-core/issues/6292
- [ ] https://github.com/medic/cht-core/issues/6650

**Comment by MaxDiz** [comment]
* deprecated initiative on Sync Status for future reference: https://github.com/medic/cht-roadmap/issues/22

**Comment by MaxDiz** [comment]
deprecated initiative on System Status Visibility for future reference: https://github.com/medic/cht-roadmap/issues/44
